USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/samsung/t-shark/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := sc8830
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := t-shark

BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8 androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048

#Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 8388608
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 8388608
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1111490560
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2457862144
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/samsung/t-shark/kernel

BOARD_HAS_NO_SELECT_BUTTON := true

#HW-Audio
BOARD_USES_TINYALSA_AUDIO := true
BOARD_USES_SS_VOIP := true

#Dither
IMAGE_DITHER_ENABLE := true

#Gralloc
USE_SPRD_DITHER := true

#hwComposer
USE_SPRD_HWCOMPOSER := true
DEVICE_USE_FB_HW_VSYNC := true
DEVICE_WITH_GSP := true
DEVICE_OVERLAYPLANE_BORROW_PRIMARYPLANE_BUFFER := true
USE_OVERLAY_COMPOSER_GPU := true
#USE_SPRD_DITHER already in use 

